allowBuilds:
  "@parcel/watcher": true
  "@swc/core": false
  esbuild: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
